### ISSUE TITLE
pls doesn't work even if I set PYTHONIOENCODING

### ISSUE THREAD

**Issue by djotaku** [dhruvkb/pls#10]
## Description
Installed pls via the pip --user install. 

Specifically:

pip install --user --upgrade pls

When I run it complains about You may need to add PYTHONIOENCODING=utf-8 to your environment and even if I do that, it doesn't work.

## Reproduction

using zsh
1. export PYTHONIOENCODING=utf8
2. pls (gives error)
3. export PYTHONIOENCODING=utf-8
4. pls (gives error)
5. export PYTHONIOENCODING="utf-8"
6. pls (gives error)
7. export PYTHONIOENCODING="utf8"
8. pls (gives error)

## Expectation
pls to run without error

## Environment

 - Device:  Desktop
 - OS:  Fedora 34
 - Browser:  N/A
 - Version:  pls 1.11.1
 - Other info: 

## Additional context
the actual commands/errors:

$ export PYTHONIOENCODING=utf-8
$ pls                          
Traceback (most recent call last):
  File "/home/ermesa/.local/bin/pls", line 8, in <module>
    sys.exit(main())
  File "/home/ermesa/.local/lib/python3.9/site-packages/pls/main.py", line 31, in main
    write_output(node_list)
  File "/home/ermesa/.local/lib/python3.9/site-packages/pls/table/table.py", line 116, in write_output
    console.print(table)
  File "/home/ermesa/.local/lib/python3.9/site-packages/rich/console.py", line 1637, in print
    self._buffer.extend(new_segments)
  File "/home/ermesa/.local/lib/python3.9/site-packages/rich/console.py", line 837, in __exit__
    self._exit_buffer()
  File "/home/ermesa/.local/lib/python3.9/site-packages/rich/console.py", line 795, in _exit_buffer
    self._check_buffer()
  File "/home/ermesa/.local/lib/python3.9/site-packages/rich/console.py", line 1929, in _check_buffer
    self.file.write(text)
UnicodeEncodeError: 'utf-8' codec can't encode character '\udccf' in position 99: surrogates not allowed
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
@djotaku can you share the output of the `locale` command on your system? That might help to reproduce the issue.

**Comment by dhruvkb** [comment]
That's pretty standard, do you have any files in the directory with Unicode characters (like emoji etc.) in the names?
