### ISSUE TITLE
Crashes on OS X Catalina with "KeyError: getgrgid(): gid not found: <number>"

### ISSUE THREAD

**Issue by barrywhart** [dhruvkb/pls#15]
## Description
When I run `pls`, it crashes every time with the error listed in the issue title.

## Reproduction

1. brew install pipx
2. pipx install pls
3. pls --help
4. See error.

## Expectation
I expected it to work correctly.

## Screenshots
```
Traceback (most recent call last):
  File "/Users/ybxh061/.local/bin/pls", line 5, in <module>
    from pls.main import main
  File "/Users/ybxh061/.local/pipx/venvs/pls/lib/python3.10/site-packages/pls/main.py", line 2, in <module>
    from pls import globals
  File "/Users/ybxh061/.local/pipx/venvs/pls/lib/python3.10/site-packages/pls/globals.py", line 124, in <module>
    state.parse_args([])  # parse a blank list of arguments as the default
  File "/Users/ybxh061/.local/pipx/venvs/pls/lib/python3.10/site-packages/pls/globals.py", line 64, in parse_args
    self.setup()
  File "/Users/ybxh061/.local/pipx/venvs/pls/lib/python3.10/site-packages/pls/globals.py", line 73, in setup
    getattr(self, f"setup_{setup_fn}")()
  File "/Users/ybxh061/.local/pipx/venvs/pls/lib/python3.10/site-packages/pls/globals.py", line 112, in setup_user_groups
    self.groups.add(getgrgid(gid).gr_name)
KeyError: 'getgrgid(): gid not found: <NUMBER>'
```

## Environment

 - Device: Macbook Pro
 - OS: 10.15.7 (Catalina)
 - Browser: Chrome
 - Version: 1.14.0
 - Other info: iTerm2 terminal

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
Hi @barrywhart, I just pushed v2.0.0 to PyPI which contains commit 3c92692. I believe that should resolve the issue. Could you try that out and verify?

**Comment by barrywhart** [comment]
Yes, it works now. Thanks!

I noticed another issue -- I'll create a separate GitHub issue for that.
