### ISSUE TITLE
"pls" crashes if run with a non-existent directory name

### ISSUE THREAD

**Issue by barrywhart** [dhruvkb/pls#16]
## Description
If I run `pls something`, and `something` is not a directory, it crashes.

## Reproduction

1. `pls something`, where `something` does not exist
2. See error.

## Expectation
I expected to see a concise error message, similar to the one `ls` prints, e.g.: 
```
ybxh061@C02YD4UEJG5H ~ % ls something
ls: something: No such file or directory
```

## Screenshots
```
ybxh061@C02YD4UEJG5H ~ % pls something
Traceback (most recent call last):
  File "/Users/ybxh061/.local/bin/pls", line 8, in <module>
    sys.exit(main())
  File "/Users/ybxh061/.local/pipx/venvs/pls/lib/python3.10/site-packages/pls/main.py", line 17, in main
    globals.state.parse_args(None)
  File "/Users/ybxh061/.local/pipx/venvs/pls/lib/python3.10/site-packages/pls/globals.py", line 63, in parse_args
    parser.parse_args(argv, namespace=self)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 1825, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 1858, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 2070, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 2026, in consume_positionals
    take_action(action, args)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 1919, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 2450, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/local/Cellar/python@3.10/3.10.2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/argparse.py", line 2483, in _get_value
    result = type_func(arg_string)
  File "/Users/ybxh061/.local/pipx/venvs/pls/lib/python3.10/site-packages/pls/arg_parser.py", line 49, in directory
    raise ExecException(f"`directory` arg should be a valid directory: {path_str}")
pls.exceptions.ExecException: `directory` arg should be a valid directory: something
```

## Environment

 - Device: Macbook Pro
 - OS: Mac OS X Catalina (10.15.7)
 - Version: 2.0.0
 - Other info: 

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
@barrywhart I just deployed version 2.1.0 to PyPI which contains improvements to exception handling. Please upgrade and try it out. Eager to know your thoughts about the updated messages.

**Comment by barrywhart** [comment]
I just tested it, and it looks great. Thanks!
