### ISSUE TITLE
OSError in `is_dir` is not catched 

### ISSUE THREAD

**Issue by gregorias** [dhruvkb/pls#18]
## Description
`is_dir` can throw an OSError, which is not catched.

```
Traceback (most recent call last):
  File "/home/grzegorzmilka/.local/bin/pls", line 8, in <module>
    sys.exit(main())
  File "/home/grzegorzmilka/.local/pipx/venvs/pls/lib/python3.9/site-packages/pls/main.py", line 102, in main
    node_map, node_list = read_input()
  File "/home/grzegorzmilka/.local/pipx/venvs/pls/lib/python3.9/site-packages/pls/fs/list.py", line 72, in read_input
    node_map = {
  File "/home/grzegorzmilka/.local/pipx/venvs/pls/lib/python3.9/site-packages/pls/fs/list.py", line 75, in <dictcomp>
    if (parsed_node := parse_node(parent_path, node))
  File "/home/grzegorzmilka/.local/pipx/venvs/pls/lib/python3.9/site-packages/pls/fs/list.py", line 38, in parse_node
    if node_path.is_dir():
  File "/usr/lib/python3.9/pathlib.py", line 1439, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
OSError: [Errno 126] Required key not available: '/home/grzegorzmilka/target'
```

## Reproduction
I don't know how to reproduce this. `target` is a symbolic link to a directory, which is inaccessible at the time of the call.

## Expectation
No error is thrown. Maybe the directory doesn't get any special symbol or is marked with red.

## Environment
 - Device: Desktop
 - OS: Debian
 - Version: 4.0.1

**Comment by dhruvkb** [comment]
While this is a major bug, it's hard to verify that it's fixed due to a lack of reproducibility. Nonetheless, I pushed a likely patch to PyPI with version 4.0.2. Please upgrade to confirm if that fixes the issue.

**Comment by gregorias** [comment]
I've found the way to reproduce a similar error:

1. Create or find a directory that's only accessible by root. E.g. with

    ```bash
    sudo mkdir root-only && sudo chmod go-rwx root-only
    ```
2. Create a symlink to a directory underneath `root-only`

    ```bash
    ln -s ./root-only/yolo yolo
    ```
3. Run `pls`.

You should see a similar stacktrace although a different error from the OS:

```
Traceback (most recent call last):
  File "/usr/bin/pls", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/pls/main.py", line 102, in main
    node_map, node_list = read_input()
  File "/usr/lib/python3.10/site-packages/pls/fs/list.py", line 72, in read_input
    node_map = {
  File "/usr/lib/python3.10/site-packages/pls/fs/list.py", line 75, in <dictcomp>
    if (parsed_node := parse_node(parent_path, node))
  File "/usr/lib/python3.10/site-packages/pls/fs/list.py", line 38, in parse_node
    if node_path.is_dir():
  File "/usr/lib/python3.10/pathlib.py", line 1303, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/usr/lib/python3.10/pathlib.py", line 1095, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/home/grzesiek/test/yolo'
```

I'll try 4.0.2 and report back.

**Comment by gregorias** [comment]
The 4.0.2 has fixed the issue and shows a nice red question mark indicating the erroneous nature. Thanks!
