### ISSUE TITLE
Exception on Windows PowerShell7

### ISSUE THREAD

**Issue by fcrespo82** [dhruvkb/pls#8]
I don't know if it has compatibility with pwsh (PowerShell 7.2.1), but it would be nice.

```
❯ pls
Traceback (most recent call last):
  File "C:\Users\fernando\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\fernando\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\fernando\AppData\Roaming\Python\Python310\Scripts\pls.exe\__main__.py", line 7, in <module>
  File "C:\Users\fernando\AppData\Roaming\Python\Python310\site-packages\pls\main.py", line 16, in main
    nodes = read_input()
  File "C:\Users\fernando\AppData\Roaming\Python\Python310\site-packages\pls\fs\list.py", line 82, in read_input
    all_nodes.sort(key=sort_key, reverse=args.sort == SortOrder.DESC)
  File "C:\Users\fernando\AppData\Roaming\Python\Python310\site-packages\pls\fs\list.py", line 31, in sort_key
    prefix = "0" if node.node_type == NodeType.DIR else "1"
  File "C:\Users\fernando\AppData\Local\Programs\Python\Python310\lib\functools.py", line 981, in __get__
    val = self.func(instance)
  File "C:\Users\fernando\AppData\Roaming\Python\Python310\site-packages\pls\models\node.py", line 82, in node_type
    node_type = get_node_type(self.path)
  File "C:\Users\fernando\AppData\Roaming\Python\Python310\site-packages\pls\fs\stats.py", line 130, in get_node_type
    raise ExecException("Could not determine type of the node.")
pls.exceptions.ExecException: Could not determine type of the node.
```

**Comment by dhruvkb** [comment]
I had tried this with Powershell and it worked okay for me. Since it was unable to determine node type, could you check if you have any special types of files in the folder?

**Comment by fcrespo82** [comment]
Hi @dhruvkb. Thanks for the response.

I was able to pinpoint a culprit in the folder I was testing.

Current dir: C:/Users/fernando

```python
Meus Documentos
Traceback (most recent call last):
  File "c:\Users\fernando\OneDrive\Área de Trabalho\tests.py", line 7, in <module>
    print(item.stat())
  File "C:\Users\fernando\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1095, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado: 'C:\\Users\\fernando\\Meus Documentos'
```

If I try to open explorer and navigate to it, I get an error too.

![image](https://user-images.githubusercontent.com/462171/154263422-c0d9cb22-9509-4a2b-948b-27062b06ad3c.png)

From what I was able to identify, this error comes from a missing junction (differs slightly from a symlink https://superuser.com/a/1291446/736809) due to moving the original folder off to a OneDrive subfolder.

This error is unrelated to your program, and it is a bug in my folder structure, nevertheless, I think it would be good to treat it gracefully and put like `node type = unkown` instead of throwing the error. 

What do you think?

Anyway, thanks for helping me find the

**Comment by dhruvkb** [comment]
That's a good idea, I'll add graceful handling of unrecognised node types to my TODOs.

**Comment by fcrespo82** [comment]
Sorry for the late reply. I've just tested with 1.11.0 and it does fix this problem.

Thanks for the great tool!
