### ISSUE TITLE
Traps on out-of-tree absolute symlinks

### ISSUE THREAD

**Issue by FrBrGeorge** [dhruvkb/pls#9]
The following two commands make `pls` trapped:
```
$ mkdir -p /tmp/dir/qq
$ ln -s /tmp/dir/qq pp
$ pls
Traceback (most recent call last):
  File "/home/george/venv/_pls/bin/pls", line 8, in <module>
    sys.exit(main())
  File "/home/george/venv/_pls/lib64/python3/site-packages/pls/main.py", line 16, in main
    node_map, node_list = read_input()
  File "/home/george/venv/_pls/lib64/python3/site-packages/pls/fs/list.py", line 82, in read_input
    node_list.sort(key=sort_key, reverse=args.sort.endswith("-"))
  File "/home/george/venv/_pls/lib64/python3/site-packages/pls/fs/list.py", line 26, in sort_key
    key = node.sort_keys[args.sort.rstrip("-")]
  File "/usr/lib64/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/george/venv/_pls/lib64/python3/site-packages/pls/models/node.py", line 207, in sort_keys
    "type": self.type_char,
  File "/usr/lib64/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/george/venv/_pls/lib64/python3/site-packages/pls/models/mixins/type.py", line 50, in type_char
    return type_char_map[self.node_type]
  File "/usr/lib64/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/home/george/venv/_pls/lib64/python3/site-packages/pls/models/mixins/type.py", line 41, in node_type
    self.populate_dest()
  File "/home/george/venv/_pls/lib64/python3/site-packages/pls/models/mixins/type.py", line 69, in populate_dest
    self.dest_node = self.__class__(name=link_path, path=link)
  File "/home/george/venv/_pls/lib64/python3/site-packages/pls/models/mixins/git.py", line 28, in __init__
    self.path_wrt_git = self.path.relative_to(state.git_root)
  File "/usr/lib64/python3.10/pathlib.py", line 816, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/tmp/dir/qq' is not in the subpath of '/home/george' OR one path is relative and the other is absolute.

```

**Comment by dhruvkb** [comment]
I ran the exact same steps and it worked for me.
<img width="1082" alt="Screenshot 2022-02-21 at 12 55 01 PM" src="https://user-images.githubusercontent.com/16580576/154921007-f4b1cbe5-ce38-4822-a81d-42f9e453ac22.png">

Are you on the latest version of `pls`? you can run `pls -v` to find out; the latest version is 1.11.0.

**Comment by awray3** [comment]
I noticed this issue too and was puzzled for a long time as to what was going on.

I spent some time in the debugger with a working example and a non-working example with symlinks. I found that the bug is caused when you are within a git repo and you try to symlink using an _absolute_ path to some directory _outside_ of the repo.

To reproduce:

```
$ mkdir ~/test; cd ~/test
$ mkdir foo; mkdir bar

# initialize git repo inside foo
$ cd foo
$ git init
$ ln -s ~/test/bar bar
$ pls # big error
```

On the other hand, relative works fine:

```
# within foo repo (after removing the absolute symlink)
$ ln -s ../bar bar
$ pls # no error
```

**Comment by dhruvkb** [comment]
Thanks @awray3, your reproduction of the issue was incredibly helpful! I've just published v1.11.1 to PyPI with commit e7d0623 that should fix this issue. @FrBrGeorge it'd be awesome if you could corroborate.

**Comment by dhruvkb** [comment]
I'm going to close this as resolved.

**Comment by FrBrGeorge** [comment]
It works, thank you
